### ISSUE TITLE
Changing factor in mfx.plot_weights() does not alter the plot

### ISSUE THREAD

**Issue by rbenfeitas** [bioFAM/mofax#19]
When running `mfx.plot_weights()` I've tried the following codes but all output plots with all factors

`mfx.plot_weights(m, factor=2, n_features=2)`
`mfx.plot_weights(m, factor='Factor2', n_features=2)`

**Comment by gtca** [comment]
This function has been renamed to `plot_weights_ranked`. Subsetting factors should work for both!

```py
mfx.plot_weights(m, factors=range(5))
mfx.plot_weights(m, factor=2)
```
