### ISSUE TITLE
Update mofax in PyPI

### ISSUE THREAD

**Issue by joewandy** [bioFAM/mofax#4]
Thank you @gtca and other maintainers for the useful package! It really helps to make sense of MOFA output in Python.

It seems that the version of mofax in PyPI is slightly old (v0.3.2, dated 22 Sept 2020). I see from setup.py that the current version in this github is v0.3.4. 

Is it possible to update the version in PyPI to be more current so it can be easily installed using `pip install`? Thanks a lot.

**Comment by gtca** [comment]
Hey @joewandy, thanks for your feedback.
I've uploaded an even more recent one, `v0.3.6`, to PyPI. In case there are any new issues with it that you might encounter, please reach out!
