### ISSUE TITLE
`plot_factor_scatter` is not working as shown in the notebook

### ISSUE THREAD

**Issue by dmalzl** [bioFAM/mofax#8]
Hi,

I am currently trying to utilise MEFISTO for the analysis of timeseries multi-omic data. For this I decided on using `mofax` for downstream analysis and so far the getting started notebook has been very helpful in learning how to use this package. However, when I try to plot different combinations of factors to see if there is any visible pattern in one or the other combination I keep getting an error associated with the `ax` parameter specified multiple times. Looking at the code this is due to `ax = ...` being collected in the `kwargs` of the `plot_factor_scatter` function and implicitly passed to `sns.scatterplot` in addition to an explicit `ax` parameter. Anyway, according to the notebook the expected behaviour would be for the `ax` to override the automated figure generation in the function and instead only using the passed `Axes` object to generate the plot (as it is indicated in the example in the notebook). Instead what the function does is collecting ax in `kwargs` and generating its own `Axes` anyway.

I would suggest to either change the example or add an explicit `ax` parameter to the `plot_factor_scatter` function to allow for a user `Axes` being used instead of generating a new one.

Best,
Daniel

**Comment by gtca** [comment]
This was an API change not reflected in the notebook — updated now.
